### ISSUE TITLE
Request for Training Code/Config

### ISSUE THREAD

**Issue by X1AOX1A** [ConiferLM/Conifer#6]
Hi Conifer Authors:

I have recently been working on reproducing the results of Conifer but noticed a significant discrepancy between my reproduced results and those reported in the paper. 

**Could you kindly share your training code or training configuration?**

## Reproduced Results  

For the SFT on Mistral-V0.1, the IFEval-LoosePrompt (epoch 4) result is 43.80, while the paper reports 50.80. Additionally, we observed that the IFEval score for epoch 3 is 48.24, but the score drops significantly in epoch 4.

## Config

Below is my reproduction configuration. I used LLaMAFactory and ran the experiment on 8 L40-48GB GPUs.

```yaml
### model
model_name_or_path: mistralai/Mistral-7B-v0.1
run_name: conifer_mistral_7b_v0.1_sft_full

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: configs/deepspeed/ds_z3_config.json

### dataset
dataset: conifer, sharegpt
template: mistral
cutoff_len: 2048
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
dataset_dir: data

### output
output_dir: saves/sft/conifer/conifer_mistral_7b_v0.1/sft_full
logging_steps: 10
# save_steps: 500
save_strategy: epoch
save_total_limit: 4
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
learning_rate: 2.0e-05
num_train_epochs: 4
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
flash_attn: fa2
ddp_timeout: 180000000
seed: 42
report_to:
 - tensorboard
 - wandb

## eval
eval_dataset: ifeval
per_device_eval_batch_size: 32
eval_strategy: steps
eval_steps: 10
do_sample: False
temperature: 0
top_k: 0
top_p: 0
```
